# Server
server {
    # Informations
    listen 80; # Open a HTTP Connection
    server_name _;

    # HTML locations
    root /usr/share/nginx/html; # HTML & Images location
    index index.html; # index filepath

    # Handling static files
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirect call to /api
    location /api/ {
        proxy_pass http://api:7000/; # Define API url
        proxy_http_version 1.1; # Use HTTP 1.1
        proxy_set_header Upgrade $http_upgrade; # Authorize Nginx to change protocol
        proxy_set_header Connection 'upgrade'; # Force connection to be upgraded
        proxy_set_header Host $host; # Send API domain name
        proxy_cache_bypass $http_upgrade; # Disable cache if update
    }
}